wget  http://luxpop.com/Material/Ac.nk
wget  http://luxpop.com/Material/Ac_llnl_cxro.nk
wget  http://luxpop.com/Material/Ag2O.nk
wget  http://luxpop.com/Material/Ag2O_llnl_cxro.nk
wget  http://luxpop.com/Material/AlAs.nk
wget  http://luxpop.com/Material/AlAs_palik.nk
wget  http://luxpop.com/Material/AlN.nk
wget  http://luxpop.com/Material/AlN_llnl_cxro.nk
wget  http://luxpop.com/Material/AlSb.nk
wget  http://luxpop.com/Material/AlSb_palik.nk
wget  http://luxpop.com/Material/a-C.nk
wget  http://luxpop.com/Material/a-C_hagemann.nk
wget  http://luxpop.com/Material/a-C_llnl_cxro.nk
wget  http://luxpop.com/Material/a-C_palik.nk
wget  http://luxpop.com/Material/a-C_windt.nk
wget  http://luxpop.com/Material/a-C_windt88.nk
wget  http://luxpop.com/Material/a-C_windt91.nk
wget  http://luxpop.com/Material/a-SiC_llnl_cxro.nk
wget  http://luxpop.com/Material/a-SiH.nk
wget  http://luxpop.com/Material/a-SiH_palik.nk
wget  http://luxpop.com/Material/B.nk
wget  http://luxpop.com/Material/B2O3.nk
wget  http://luxpop.com/Material/B2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/B4C.nk
wget  http://luxpop.com/Material/B4C_llnl_cxro.nk
wget  http://luxpop.com/Material/BN.nk
wget  http://luxpop.com/Material/BN_llnl_cxro.nk
wget  http://luxpop.com/Material/B_llnl_cxro.nk
wget  http://luxpop.com/Material/Be.nk
wget  http://luxpop.com/Material/BeO.nk
wget  http://luxpop.com/Material/BeO_llnl_cxro.nk
wget  http://luxpop.com/Material/BeO_palik.nk
wget  http://luxpop.com/Material/Be_llnl_cxro.nk
wget  http://luxpop.com/Material/Be_palik.nk
wget  http://luxpop.com/Material/C10H8O4.nk
wget  http://luxpop.com/Material/C10H8O4_llnl_cxro.nk
wget  http://luxpop.com/Material/C5H8O2.nk
wget  http://luxpop.com/Material/C5H8O2_llnl_cxro.nk
wget  http://luxpop.com/Material/	CH2.nk
wget  http://luxpop.com/Material/CH2CCl2.nk
wget  http://luxpop.com/Material/CH2CCl2_llnl_cxro.nk
wget  http://luxpop.com/Material/CH2_llnl_cxro.nk
wget  http://luxpop.com/Material/Co2O3.nk
wget  http://luxpop.com/Material/Co2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/Co3O4.nk
wget  http://luxpop.com/Material/Co3O4_llnl_cxro.nk
wget  http://luxpop.com/Material/CoO.nk
wget  http://luxpop.com/Material/CoO_llnl_cxro.nk
wget  http://luxpop.com/Material/CoSi2.nk
wget  http://luxpop.com/Material/CoSi2_llnl_cxro.nk
wget  http://luxpop.com/Material/Cr.nk
wget  http://luxpop.com/Material/Cr2O3.nk
wget  http://luxpop.com/Material/Cr2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/Cr3C2.nk
wget  http://luxpop.com/Material/Cr3C2_llnl_cxro.nk
wget  http://luxpop.com/Material/Cr3C2_windt.nk
wget  http://luxpop.com/Material/CsI.nk
wget  http://luxpop.com/Material/CsI_llnl_cxro.nk
wget  http://luxpop.com/Material/CsI_palik.nk
wget  http://luxpop.com/Material/Cu2O.nk
wget  http://luxpop.com/Material/Cu2O_llnl_cxro.nk
wget  http://luxpop.com/Material/Cu2O_palik.nk
wget  http://luxpop.com/Material/Cu4Si.nk
wget  http://luxpop.com/Material/Cu4Si_llnl_cxro.nk
wget  http://luxpop.com/Material/CuO.nk
wget  http://luxpop.com/Material/CuO_llnl_cxro.nk
wget  http://luxpop.com/Material/CuO_palik.nk
wget  http://luxpop.com/Material/Cu_llnl_cxro.nk
wget  http://luxpop.com/Material/Cu_palik.nk
wget  http://luxpop.com/Material/d-C.nk
wget  http://luxpop.com/Material/d-C_llnl_cxro.nk
wget  http://luxpop.com/Material/d-C_palik.nk
wget  http://luxpop.com/Material/d-C_windt.nk
wget  http://luxpop.com/Material/Fe2O3.nk
wget  http://luxpop.com/Material/Fe2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/Fe3O4.nk
wget  http://luxpop.com/Material/Fe3O4_llnl_cxro.nk
wget  http://luxpop.com/Material/	FeO.nk
wget  http://luxpop.com/Material/FeO_llnl_cxro.nk
wget  http://luxpop.com/Material/g-C.nk
wget  http://luxpop.com/Material/g-C_llnl_cxro.nk
wget  http://luxpop.com/Material/Hf-te_lynch.nk
wget  http://luxpop.com/Material/Hf-tm_lynch.nk
wget  http://luxpop.com/Material/Hf.nk
wget  http://luxpop.com/Material/HfO2.nk
wget  http://luxpop.com/Material/HfO2_llnl_cxro.nk
wget  http://luxpop.com/Material/Hf_llnl_cxro.nk
wget  http://luxpop.com/Material/Hf_windt.nk
wget  http://luxpop.com/Material/Hg.nk
wget  http://luxpop.com/Material/HgTe.nk
wget  http://luxpop.com/Material/HgTe_palik.nk
wget  http://luxpop.com/Material/Hg_llnl_cxro.nk
wget  http://luxpop.com/Material/Hg_palik.nk
wget  http://luxpop.com/Material/Ir.nk
wget  http://luxpop.com/Material/Ir_llnl_cxro.nk
wget  http://luxpop.com/Material/Ir_palik.nk
wget  http://luxpop.com/Material/Ir_windt.nk
wget  http://luxpop.com/Material/ir-ZnS.nk
wget  http://luxpop.com/Material/ir-ZnS_palik.nk
wget  http://luxpop.com/Material/ir-ZnSe.nk
wget  http://luxpop.com/Material/ir-ZnSe_palik.nk
wget  http://luxpop.com/Material/K.nk
wget  http://luxpop.com/Material/KBr.nk
wget  http://luxpop.com/Material/KBr_palik.nk
wget  http://luxpop.com/Material/KCl.nk
wget  http://luxpop.com/Material/KCl_palik.nk
wget  http://luxpop.com/Material/K_palik.nk
wget  http://luxpop.com/Material/Li.nk
wget  http://luxpop.com/Material/Li_palik.nk
wget  http://luxpop.com/Material/Mg.nk
wget  http://luxpop.com/Material/MgO.nk
wget  http://luxpop.com/Material/MgO_llnl_cxro.nk
wget  http://luxpop.com/Material/MgO_palik.nk
wget  http://luxpop.com/Material/Mg_llnl_cxro.nk
wget  http://luxpop.com/Material/Mn.nk
wget  http://luxpop.com/Material/Mn3O4.nk
wget  http://luxpop.com/Material/	Mn3O4_llnl_cxro.nk
wget  http://luxpop.com/Material/MnO2.nk
wget  http://luxpop.com/Material/MnO2_llnl_cxro.nk
wget  http://luxpop.com/Material/Mo.nk
wget  http://luxpop.com/Material/Mo2C.nk
wget  http://luxpop.com/Material/Mo2C_llnl_cxro.nk
wget  http://luxpop.com/Material/MoC.nk
wget  http://luxpop.com/Material/MoC_llnl_cxro.nk
wget  http://luxpop.com/Material/MoO2.nk
wget  http://luxpop.com/Material/MoO2_llnl_cxro.nk
wget  http://luxpop.com/Material/MoO3.nk
wget  http://luxpop.com/Material/MoO3_llnl_cxro.nk
wget  http://luxpop.com/Material/MoS2.nk
wget  http://luxpop.com/Material/MoS2_llnl_cxro.nk
wget  http://luxpop.com/Material/MoSi2.nk
wget  http://luxpop.com/Material/MoSi2_llnl_cxro.nk
wget  http://luxpop.com/Material/MoSi2_windt.nk
wget  http://luxpop.com/Material/Mo_llnl_cxro.nk
wget  http://luxpop.com/Material/Mo_palik.nk
wget  http://luxpop.com/Material/Mo_windt88.nk
wget  http://luxpop.com/Material/Mo_windt91.nk
wget  http://luxpop.com/Material/Mo_windt92.nk
wget  http://luxpop.com/Material/NaCl.nk
wget  http://luxpop.com/Material/NaCl_palik.nk
wget  http://luxpop.com/Material/Na_palik.nk
wget  http://luxpop.com/Material/Nb.nk
wget  http://luxpop.com/Material/NbO.nk
wget  http://luxpop.com/Material/NbO2.nk
wget  http://luxpop.com/Material/NbO2_llnl_cxro.nk
wget  http://luxpop.com/Material/NbO_llnl_cxro.nk
wget  http://luxpop.com/Material/Nb_llnl_cxro.nk
wget  http://luxpop.com/Material/Nb_palik.nk
wget  http://luxpop.com/Material/Nb_weaver.nk
wget  http://luxpop.com/Material/Nb_windt.nk
wget  http://luxpop.com/Material/Ni.8Cr.2.nk
wget  http://luxpop.com/Material/Ni.8Cr.2_llnl_cxro.nk
wget  http://luxpop.com/Material/Ni.93V.07.nk
wget  http://luxpop.com/Material/Ni.93V.07_llnl_cxro.nk
wget  http://luxpop.com/Material/NiO.nk
wget  http://luxpop.com/Material/	NiO_llnl_cxro.nk
wget  http://luxpop.com/Material/Ni_llnl_cxro.nk
wget  http://luxpop.com/Material/Ni_palik.nk
wget  http://luxpop.com/Material/Os.nk
wget  http://luxpop.com/Material/OsO2.nk
wget  http://luxpop.com/Material/OsO2_llnl_cxro.nk
wget  http://luxpop.com/Material/Os_llnl_cxro.nk
wget  http://luxpop.com/Material/Os_lynch.nk
wget  http://luxpop.com/Material/Os_palik.nk
wget  http://luxpop.com/Material/Os_windt.nk
wget  http://luxpop.com/Material/PdO.nk
wget  http://luxpop.com/Material/PdO_llnl_cxro.nk
wget  http://luxpop.com/Material/PtO.nk
wget  http://luxpop.com/Material/PtO2.nk
wget  http://luxpop.com/Material/PtO2_llnl_cxro.nk
wget  http://luxpop.com/Material/PtO_llnl_cxro.nk
wget  http://luxpop.com/Material/Re-te_lynch.nk
wget  http://luxpop.com/Material/Re-tm_lynch.nk
wget  http://luxpop.com/Material/Re.nk
wget  http://luxpop.com/Material/Re2O7.nk
wget  http://luxpop.com/Material/Re2O7_llnl_cxro.nk
wget  http://luxpop.com/Material/ReO2.nk
wget  http://luxpop.com/Material/ReO2_llnl_cxro.nk
wget  http://luxpop.com/Material/ReO3.nk
wget  http://luxpop.com/Material/ReO3_llnl_cxro.nk
wget  http://luxpop.com/Material/Re_llnl_cxro.nk
wget  http://luxpop.com/Material/Re_windt.nk
wget  http://luxpop.com/Material/Rh.nk
wget  http://luxpop.com/Material/Rh2O3.nk
wget  http://luxpop.com/Material/Rh2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/Rh_llnl_cxro.nk
wget  http://luxpop.com/Material/Rh_palik.nk
wget  http://luxpop.com/Material/Rh_weaver.nk
wget  http://luxpop.com/Material/Rh_windt.nk
wget  http://luxpop.com/Material/RuO2.nk
wget  http://luxpop.com/Material/RuO2_llnl_cxro.nk
wget  http://luxpop.com/Material/RuO4.nk
wget  http://luxpop.com/Material/RuO4_llnl_cxro.nk
wget  http://luxpop.com/Material/RuSi.nk
wget  http://luxpop.com/Material/	RuSi_llnl_cxro.nk
wget  http://luxpop.com/Material/Ru_cox.nk
wget  http://luxpop.com/Material/Ru_llnl_cxro.nk
wget  http://luxpop.com/Material/Ru_weaver.nk
wget  http://luxpop.com/Material/Ru_windt88.nk
wget  http://luxpop.com/Material/Ru_windt92.nk
wget  http://luxpop.com/Material/Sc.nk
wget  http://luxpop.com/Material/Sc2O3.nk
wget  http://luxpop.com/Material/Sc2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/ScN.nk
wget  http://luxpop.com/Material/ScN_llnl_cxro.nk
wget  http://luxpop.com/Material/Sc_llnl_cxro.nk
wget  http://luxpop.com/Material/Se-e.nk
wget  http://luxpop.com/Material/Se-e_palik.nk
wget  http://luxpop.com/Material/Se.nk Se_palik.nk
wget  http://luxpop.com/Material/SiC.nk
wget  http://luxpop.com/Material/SiC_llnl_cxro.nk
wget  http://luxpop.com/Material/SiC_osantowski.nk
wget  http://luxpop.com/Material/SiC_palik.nk
wget  http://luxpop.com/Material/SiC_windt.nk
wget  http://luxpop.com/Material/SiC_yanagihara.nk
wget  http://luxpop.com/Material/SiO.nk
wget  http://luxpop.com/Material/Sn.nk
wget  http://luxpop.com/Material/SnO.nk
wget  http://luxpop.com/Material/SnO2.nk
wget  http://luxpop.com/Material/SnO2_llnl_cxro.nk
wget  http://luxpop.com/Material/SnO_llnl_cxro.nk
wget  http://luxpop.com/Material/SnTe.nk
wget  http://luxpop.com/Material/SnTe_palik.nk
wget  http://luxpop.com/Material/Sn_llnl_cxro.nk
wget  http://luxpop.com/Material/Ta.nk
wget  http://luxpop.com/Material/Ta2O5.nk
wget  http://luxpop.com/Material/Ta2O5_llnl_cxro.nk
wget  http://luxpop.com/Material/TaC.nk
wget  http://luxpop.com/Material/TaC_llnl_cxro.nk
wget  http://luxpop.com/Material/TaN.nk
wget  http://luxpop.com/Material/TaN_llnl_cxro.nk
wget  http://luxpop.com/Material/Ta_llnl_cxro.nk
wget  http://luxpop.com/Material/Ta_palik.nk
wget  http://luxpop.com/Material/Ta_weaver.nk
wget  http://luxpop.com/Material/	Ta_windt.nk
wget  http://luxpop.com/Material/Te-e.nk
wget  http://luxpop.com/Material/Te-e_palik.nk
wget  http://luxpop.com/Material/Te.nk
wget  http://luxpop.com/Material/Te_palik.nk
wget  http://luxpop.com/Material/ThF4.nk
wget  http://luxpop.com/Material/ThF4_palik.nk
wget  http://luxpop.com/Material/TiC.nk
wget  http://luxpop.com/Material/TiC_llnl_cxro.nk
wget  http://luxpop.com/Material/TiC_palik.nk
wget  http://luxpop.com/Material/TiN.nk
wget  http://luxpop.com/Material/TiN_llnl_cxro.nk
wget  http://luxpop.com/Material/TiN_palik.nk
wget  http://luxpop.com/Material/TiO2-e.nk
wget  http://luxpop.com/Material/TiO2-e_palik.nk
wget  http://luxpop.com/Material/TiO2.nk
wget  http://luxpop.com/Material/TiO2_llnl_cxro.nk
wget  http://luxpop.com/Material/TiO2_palik.nk
wget  http://luxpop.com/Material/V2O3.nk
wget  http://luxpop.com/Material/V2O3_llnl_cxro.nk
wget  http://luxpop.com/Material/V2O5.nk
wget  http://luxpop.com/Material/V2O5_llnl_cxro.nk
wget  http://luxpop.com/Material/VC.nk
wget  http://luxpop.com/Material/VC_llnl_cxro.nk
wget  http://luxpop.com/Material/VC_palik.nk
wget  http://luxpop.com/Material/VN.nk
wget  http://luxpop.com/Material/VN_llnl_cxro.nk
wget  http://luxpop.com/Material/VN_palik.nk
wget  http://luxpop.com/Material/VO.nk
wget  http://luxpop.com/Material/VO2.nk
wget  http://luxpop.com/Material/VO2_llnl_cxro.nk
wget  http://luxpop.com/Material/VO_llnl_cxro.nk
wget  http://luxpop.com/Material/V_kihara.nk
wget  http://luxpop.com/Material/V_llnl_cxro.nk
wget  http://luxpop.com/Material/V_palik.nk
wget  http://luxpop.com/Material/V_weaver.nk
wget  http://luxpop.com/Material/W.nk
wget  http://luxpop.com/Material/WO2.nk
wget  http://luxpop.com/Material/WO2_llnl_cxro.nk
